language: generic
sudo: required

install:
  - |
    if [ ! -f "$HOME/miniconda/condabin/conda" ]; then

      echo "installing miniconda"
      rm -rf $HOME/miniconda
      mkdir -p $HOME/download
      curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o $HOME/download/miniconda.sh
      bash $HOME/download/miniconda.sh -b -p $HOME/miniconda

      export PATH=$HOME/miniconda/bin:$PATH

      conda config --set always_yes yes --set changeps1 no
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda update -q conda
      conda info -a

      conda create -q -n test-env \
        python=3.7 \
        pip \
        setuptools
      
      source activate test-env
      conda install -q -c stackvana stackvana
    else
      export PATH=$HOME/miniconda/bin:$PATH
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda update -q conda
      conda info -a
      source activate test-env
    fi
    
    conda install -q \
      flake8 \
      pytest \
      galsim \
      ngmix \
      numpy

    pip install --no-deps git+https://github.com/LSSTDESC/wl-shear-testing-sims.git
    pip install --no-deps -e .

script:
  - flake8 descwl_coadd
  - pytest -vv descwl_coadd
