name: tests

on:
      push:
          branches:
              - master
      pull_request: null

jobs:
    tests:
      name: tests
      strategy:
          matrix:
            pyver: [3.8]

      runs-on: "ubuntu-latest"

      steps:
          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
                python-version: ${{ matrix.pyver }}
                channels: conda-forge
                channel-priority: strict
                show-channel-urls: true

          - name: Install special dependencies with conda and pip
            shell: bash -l {0}
            run: |
                conda config --set always_yes yes
                conda install -q mamba

                mamba install -q stackvana=0

                mamba install -q \
                  flake8 \
                  pytest \
                  numpy \
                  galsim \
                  numba \
                  ngmix \
                  lsstdesc-weaklensingdeblending \
                  fitsio

                pip install --no-deps git+https://github.com/LSSTDESC/descwl-shear-sims.git

                mkdir /tmp
                git clone --branch u/erykoff/onlinecoadd https://github.com/lsst/pipe_tasks.git /tmp/pipe_tasks
                pushd /tmp/pipe_tasks
                # this might partly fail but that's ok
                scons
                popd

                pip install --no-deps -e .

          - name: Lint with flake8
            shell: bash -l {0}
            run: |
                . /usr/local/share/stackvana-activate.sh
                flake8 descwl_coadd

          - name: Run pytest
            shell: bash -l {0}
            run: |
                setup -j -r /tmp/pipe_tasks
                pytest -vv descwl_coadd
