name: tests

on:
      push:
          branches:
              - master
      pull_request: null

jobs:
    tests:
      name: tests
      strategy:
          matrix:
            # specific version 3.8.8 is here to fix solver error w/ sqlite 
            # see https://lsstc.slack.com/archives/C2K9RHYTV/p1628567486002200
            pyver: [3.8.8]

      runs-on: "ubuntu-latest"

      steps:
          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
                python-version: ${{ matrix.pyver }}
                channels: conda-forge
                channel-priority: strict
                show-channel-urls: true

          - name: Install special dependencies with conda and pip
            shell: bash -l {0}
            run: |
                conda config --set always_yes yes
                conda install -q mamba

                mamba install -q stackvana=0.2021.32

                mamba install -q \
                  flake8 \
                  pytest \
                  numpy \
                  galsim \
                  numba \
                  ngmix \
                  lsstdesc-weaklensingdeblending \
                  fitsio

                pip install --no-deps git+https://github.com/LSSTDESC/descwl-shear-sims.git

          - name: Lint with flake8
            shell: bash -l {0}
            run: |
                flake8 descwl_coadd

          - name: Run pytest
            shell: bash -l {0}
            run: |
                pytest -vv descwl_coadd
